server:
  port: 8443
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always
spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 120MB
  main:
    allow-circular-references: true
  
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://localhost:5432/fin_db
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    password: fbkxdefanqpycbev
    port: 587
    username: aspanadam@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
  level:
    root: "debug"
    org.hibernate: "error"
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){green} [%level] %c{1.} [%t] %m%n"
