spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mail:
    host: smtp.gmail.com
    username: aspanadam@gmail.com
    properties:
      mail:
        smtp:
          starttls:
            required: 'true'
            enable: 'true'
          auth: 'true'
    port: '587'
    password: hbiscaqyyjdutjoe
  datasource:
    password: RfPi9t8ZVs00J4I9TB7mODjFeYXaTkDN
    username: auth_db_0lin_user
    url: jdbc:postgresql://dpg-chbq1d2k728tp9fncji0-a.frankfurt-postgres.render.com:5432/auth_db_0lin
server:
  error:
    include-stacktrace: always
    include-exception: 'true'
    include-message: always