spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mail:
    host: smtp.gmail.com
    username: aspanadam@gmail.com
    properties:
      mail:
        smtp:
          starttls:
            required: 'true'
            enable: 'true'
          auth: 'true'
    port: '587'
    password: hbiscaqyyjdutjoe
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://localhost:5432/auth_db
server:
  error:
    include-stacktrace: always
    include-exception: 'true'
    include-message: always